# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  download:
    cmd: stages/1_download.sh
    deps:
      - stages/1_download.sh
    outs:
      - download